<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>KinopoiskWhite</AssemblyName>
    <RootNamespace>KinopoiskWhite</RootNamespace>
    
    <DebugType>portable</DebugType>
  </PropertyGroup>

   <ItemGroup>
    <PackageReference Include="Jellyfin.Data" Version="10.*-*" />
    <PackageReference Include="Jellyfin.Controller" Version="10.*-*" />
    <PackageReference Include="Jellyfin.Common" Version="10.*-*" />
    <PackageReference Include="Jellyfin.Model" Version="10.*-*" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />

    <EmbeddedResource Include="Api\Queries\*.gql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>

    <EmbeddedResource Include="Common\config.html">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

</Project>
